defaults:
  - scope:
      collection: "posts"
    values:
      layout: "post"
kramdown:
  smart_quotes: lsquo,rsquo,bdquo,rdquo
  header_links: true
picture:
  output: "g"
  ignore_missing_images: true
